# Trigger: force workflow file refresh - 2025-07-13T23:45:00Z
name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Add project root to PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      - name: Run Python tests
        run: pytest
      - name: Build and start services with docker-compose
        run: docker-compose up -d --build webservice test-eval
      - name: Wait for test-eval to finish and show logs
        run: |
          docker-compose logs -f --tail=100 test-eval || true
          docker-compose ps
      - name: Tear down docker-compose
        if: always()
        run: docker-compose down --volumes --remove-orphans 